//! Task M9.5.8: the refit's samples, statistics, budgets, weights and the CLI text, over
//! the recorded history fixtures in `daemon/tests/fixtures/history/` (generated by the
//! rules below and compared byte for byte).

use std::path::{Path, PathBuf};

use proto::{
    Budget, ClassBudget, DiffStats, Effort, GateCounts, GateTally, HISTORY_VERSION, HistoryLine,
    PathWeights, PhaseSecs, RefitState, RevertRecord, Route, RunPath, Runtime, SeverityTally, Size,
    Strength, TaskKind, TaskOrigin, TaskOutcome, TaskPattern, TaskRecord, TestMode, TokenUsage,
    TuningFile,
};

use super::{
    SizeClass, active_secs, budget_samples, ceiling, class_of, lower_median, percentile, refit,
    report, route_samples, threshold_samples, tuned,
};

/// `refit_budget`'s `now`, and the CLI block's (review ruling I5): 2026-09-27 09:06:40
/// UTC.
pub(super) const NOW: u64 = 1_790_500_000;

/// One fixture record (the brief's common rule): a merged plan code task of size S
/// with `tool_calls`, `w` working seconds and `lines` added lines.
pub(super) fn record(
    run: &str,
    task: u32,
    at: u64,
    tool_calls: u32,
    w: u64,
    lines: u32,
) -> TaskRecord {
    TaskRecord {
        v: HISTORY_VERSION,
        record_id: format!("{run}/t{task}"),
        at,
        run_id: run.into(),
        task_id: format!("t{task}"),
        path: Some(RunPath::Plan),
        kind: TaskKind::Code,
        hub: false,
        test_mode: TestMode::Tdd,
        planned_size: Size::S,
        final_size: Size::S,
        size_check: None,
        route: Route {
            runtime: Runtime::Claude,
            model: "claude-sonnet-5".into(),
            strength: Strength::Standard,
            effort: Effort::Low,
        },
        review_routes: Vec::new(),
        routing_decisions: Vec::new(),
        outcome: TaskOutcome::Merged,
        block: None,
        diff: Some(DiffStats {
            files: 1,
            hunks: 1,
            added: lines,
            removed: 0,
        }),
        tool_calls,
        worker_usage: TokenUsage::default(),
        reviewer_usage: TokenUsage::default(),
        decider_usage: TokenUsage::default(),
        phases: PhaseSecs {
            queued: 5,
            preparing: 20,
            working: w,
            proof: 0,
            check: 40,
            review: 60,
            merge: 10,
            blocked: 0,
        },
        wall_secs: 0,
        gates: GateTally::default(),
        severities: SeverityTally::default(),
        bounces: GateCounts::default(),
        failures: 0,
        stalls: 0,
        budget_exceeded: 0,
        conflicts: 0,
        max_rung: 0,
        sessions: 1,
        done_signal: None,
        merge_commit: None,
        stage: 1,
        origin: TaskOrigin::Plan,
        pattern: None,
        race_winner: None,
        race_adopted: false,
        writer_failures: 0,
        round: 1,
    }
}

/// `record` made size M (`hub` or not), with M's route.
fn sized_m(mut r: TaskRecord, hub: bool) -> TaskRecord {
    r.planned_size = Size::M;
    r.final_size = Size::M;
    r.hub = hub;
    r.route.effort = Effort::Medium;
    r
}

fn task(r: TaskRecord) -> HistoryLine {
    HistoryLine::Task(r)
}

/// The 34 S records of `refit.jsonl`.
fn refit_s() -> Vec<HistoryLine> {
    (0..34u32)
        .map(|i| {
            let run = format!("r{}", 1 + i / 10);
            let at = 1_790_000_000 + 60 * u64::from(i);
            let mut r = record(&run, i, at, 6 + i, 260 + 10 * u64::from(i), 3 + i);
            r.max_rung = if i < 14 { 2 } else { 0 };
            task(r)
        })
        .collect()
}

/// Each fixture's records, built by its rule (the brief's "The fixtures"). Rules the
/// brief leaves open: every record has `sessions = 1`; the M records are of runs `m1`
/// and `m2` (`1 + j / 10`, as S's), not one run `m1`, whose cap of 10 per run and
/// round would show `10/30` against the CLI block's `12/30`; the hub records follow M's rule
/// with `at = 1_790_150_000 + 60 × j`; `quality.jsonl` numbers its tasks within each run
/// (`q2/t3` exists for the bisect culprit) at `1_790_300_000 + 60 × i`, with 20 tool
/// calls, 400 working seconds and 10 lines each.
pub(super) fn fixture_records(name: &str) -> Vec<HistoryLine> {
    match name {
        "refit" => {
            let mut lines = refit_s();
            lines.extend((0..12u32).map(|j| {
                let run = format!("m{}", 1 + j / 10);
                let at = 1_790_100_000 + 60 * u64::from(j);
                task(sized_m(record(&run, j, at, 60 + j, 1500, 50 + j), false))
            }));
            lines.extend((0..3u32).map(|j| {
                let at = 1_790_150_000 + 60 * u64::from(j);
                task(sized_m(record("h1", j, at, 60 + j, 1500, 50 + j), true))
            }));
            lines
        }
        "too-few" => refit_s().into_iter().take(29).collect(),
        "outlier-run" => {
            let mut lines = refit_s();
            lines.extend((0..25u32).map(|j| {
                let at = 1_790_200_000 + 60 * u64::from(j);
                task(record("r9", j, at, 900, 9000, 900))
            }));
            lines
        }
        "quality" => (0..30u32)
            .map(|i| {
                let run = format!("q{}", 1 + i / 10);
                let at = 1_790_300_000 + 60 * u64::from(i);
                task(record(&run, i % 10, at, 20, 400, 10))
            })
            .collect(),
        other => panic!("no fixture {other}"),
    }
}

pub(super) const FIXTURES: [&str; 4] = ["refit", "too-few", "outlier-run", "quality"];

fn fixture_path(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("tests/fixtures/history/{name}.jsonl"))
}

fn jsonl(lines: &[HistoryLine]) -> String {
    let mut out = String::new();
    for line in lines {
        out.push_str(&serde_json::to_string(line).unwrap());
        out.push('\n');
    }
    out
}

pub(super) fn ids(records: &[&TaskRecord]) -> Vec<String> {
    records.iter().map(|r| r.record_id.clone()).collect()
}

pub(super) fn budget(tool_calls: u32, minutes: u32) -> Budget {
    Budget {
        tool_calls,
        minutes,
        tokens: None,
    }
}

#[test]
fn fixtures_match_their_rules() {
    for name in FIXTURES {
        let path = fixture_path(name);
        let on_disk = std::fs::read_to_string(&path).unwrap();
        assert_eq!(on_disk, jsonl(&fixture_records(name)), "{}", path.display());
        let (read, problems) = super::super::history_io::read_history(&path);
        assert!(problems.is_empty(), "{problems:?}");
        assert_eq!(read, fixture_records(name), "{name}");
    }
}

#[test]
fn lower_median_and_percentile_are_integer_and_exact() {
    assert_eq!(lower_median(&mut [3, 1, 2]), Some(2));
    assert_eq!(lower_median(&mut [4, 1, 3, 2]), Some(2));
    assert_eq!(lower_median(&mut []), None);
    let mut values: Vec<u64> = (1..=34).rev().collect();
    assert_eq!(percentile(&mut values, 90), Some(31));
    assert_eq!(percentile(&mut [], 90), None);
    assert_eq!(percentile(&mut [7], 90), Some(7));
    let phases = PhaseSecs {
        queued: 5,
        preparing: 1,
        working: 2,
        proof: 4,
        check: 8,
        review: 16,
        merge: 32,
        blocked: 64,
    };
    assert_eq!(
        active_secs(&phases),
        63,
        "queued and blocked are not active"
    );
}

#[test]
fn samples_take_plan_code_tasks_only() {
    let t = config::Tuning::default();
    let plan = record("r1", 0, 100, 10, 100, 5);
    let mut lines = vec![task(plan.clone())];
    for (i, origin) in [
        TaskOrigin::Bisect,
        TaskOrigin::Sync,
        TaskOrigin::Ci,
        TaskOrigin::Review,
    ]
    .into_iter()
    .enumerate()
    {
        let mut r = record("r1", 10 + i as u32, 100, 10, 100, 5);
        r.origin = origin;
        lines.push(task(r));
    }
    for (i, kind) in [TaskKind::Research, TaskKind::Review, TaskKind::Docs]
        .into_iter()
        .enumerate()
    {
        let mut r = record("r1", 20 + i as u32, 100, 10, 100, 5);
        r.kind = kind;
        lines.push(task(r));
    }
    let only = vec![plan.record_id.clone()];
    assert_eq!(ids(&budget_samples(&lines, SizeClass::S, &t)), only);
    assert_eq!(ids(&threshold_samples(&lines, SizeClass::S, &t)), only);
    assert_eq!(ids(&route_samples(&lines, SizeClass::S, &t)), only);
}

#[test]
fn samples_filter_cap_and_window() {
    let t = config::Tuning::default();
    let keep = record("r1", 0, 100, 10, 100, 5);
    let mut without_approval = record("r1", 1, 100, 10, 100, 5);
    without_approval.outcome = TaskOutcome::MergedWithoutApproval;
    let reverted = record("r1", 2, 100, 10, 100, 5);
    let run_reverted = record("r2", 0, 100, 10, 100, 5);
    let mut raced = record("r1", 3, 100, 10, 100, 5);
    raced.pattern = Some(TaskPattern::Race);
    let mut paired = record("r1", 4, 100, 10, 100, 5);
    paired.pattern = Some(TaskPattern::Pair);
    let mut large = record("r1", 5, 100, 10, 100, 5);
    large.final_size = Size::L;
    let mut no_diff = record("r1", 6, 100, 10, 100, 5);
    no_diff.diff = None;
    let mut blocked = record("r1", 7, 100, 10, 100, 5);
    blocked.outcome = TaskOutcome::Blocked;
    let mut never_ran = record("r1", 8, 100, 10, 100, 5);
    never_ran.outcome = TaskOutcome::Blocked;
    never_ran.sessions = 0;
    let revert = |run: &str, task: Option<&str>, n: u32| {
        HistoryLine::Revert(RevertRecord {
            v: HISTORY_VERSION,
            record_id: format!("revert/{n}"),
            at: 200,
            run_id: run.into(),
            task_id: task.map(str::to_string),
            reverted: format!("merge{n}"),
            revert_commit: format!("rev{n}"),
        })
    };
    let lines: Vec<HistoryLine> = [
        &keep,
        &without_approval,
        &reverted,
        &run_reverted,
        &raced,
        &paired,
        &large,
        &no_diff,
        &blocked,
        &never_ran,
    ]
    .into_iter()
    .map(|r| task(r.clone()))
    .chain([revert("r1", Some("t2"), 1), revert("r2", None, 2)])
    .collect();
    let s = SizeClass::S;
    assert_eq!(
        ids(&budget_samples(&lines, s, &t)),
        ["r1/t0", "r1/t4", "r1/t6"]
    );
    assert_eq!(ids(&threshold_samples(&lines, s, &t)), ["r1/t0", "r1/t4"]);
    // Route samples: whatever the outcome, with a session; a race never.
    assert_eq!(
        ids(&route_samples(&lines, s, &t)),
        [
            "r1/t0", "r1/t1", "r1/t2", "r1/t4", "r1/t6", "r1/t7", "r2/t0"
        ]
    );

    // The per-(run, round) cap keeps the newest.
    let capped = config::Tuning {
        per_run_cap: 2,
        ..config::Tuning::default()
    };
    let one_round: Vec<HistoryLine> = (0..5u32)
        .map(|i| task(record("r1", i, 100 + u64::from(i), 10, 100, 5)))
        .collect();
    assert_eq!(
        ids(&budget_samples(&one_round, s, &capped)),
        ["r1/t3", "r1/t4"]
    );
    let two_rounds: Vec<HistoryLine> = (0..10u32)
        .map(|i| {
            let mut r = record("r1", i, 100 + u64::from(i), 10, 100, 5);
            r.round = 1 + i / 5;
            task(r)
        })
        .collect();
    assert_eq!(
        ids(&budget_samples(&two_rounds, s, &capped)),
        ["r1/t3", "r1/t4", "r1/t8", "r1/t9"]
    );
    // Round 0 (a line written before 9.5) reads as round 1.
    let mut old = one_round.clone();
    if let HistoryLine::Task(r) = &mut old[0] {
        r.round = 0;
        r.at = 200;
    }
    assert_eq!(ids(&budget_samples(&old, s, &capped)), ["r1/t4", "r1/t0"]);

    // The window keeps the newest.
    let windowed = config::Tuning {
        window: 3,
        ..config::Tuning::default()
    };
    assert_eq!(
        ids(&budget_samples(&one_round, s, &windowed)),
        ["r1/t2", "r1/t3", "r1/t4"]
    );
}

/// Controller addendum (from the 4a review): the filter reads the reverts in effect, so
/// a task whose revert was itself reverted is a sample again.
#[test]
fn a_revert_of_a_revert_makes_the_task_a_sample_again() {
    let t = config::Tuning::default();
    let revert = |n: u32, reverted: &str| {
        HistoryLine::Revert(RevertRecord {
            v: HISTORY_VERSION,
            record_id: format!("revert/{n}"),
            at: 200 + u64::from(n),
            run_id: "r1".into(),
            task_id: Some("t0".into()),
            reverted: reverted.into(),
            revert_commit: format!("rev{n}"),
        })
    };
    let mut lines = vec![task(record("r1", 0, 100, 10, 100, 5)), revert(1, "merge0")];
    assert!(budget_samples(&lines, SizeClass::S, &t).is_empty());
    lines.push(revert(2, "rev1"));
    assert_eq!(ids(&budget_samples(&lines, SizeClass::S, &t)), ["r1/t0"]);
    lines.push(revert(3, "rev2"));
    assert!(budget_samples(&lines, SizeClass::S, &t).is_empty());
}

#[test]
fn class_of_moved_from_stats_unchanged() {
    let s = record("r", 0, 0, 0, 0, 0);
    assert_eq!(class_of(&s), Some(SizeClass::S));
    assert_eq!(class_of(&sized_m(s.clone(), false)), Some(SizeClass::M));
    assert_eq!(class_of(&sized_m(s.clone(), true)), Some(SizeClass::Hub));
    let mut l = s.clone();
    l.final_size = Size::L;
    assert_eq!(class_of(&l), None);
    l.hub = true;
    assert_eq!(class_of(&l), Some(SizeClass::Hub));
    assert_eq!(
        [SizeClass::S, SizeClass::M, SizeClass::Hub].map(SizeClass::label),
        ["S", "M", "hub"]
    );
    assert_eq!(
        [SizeClass::S, SizeClass::M, SizeClass::Hub].map(SizeClass::key),
        ["s", "m", "hub"]
    );
}

#[test]
fn refit_fixture_budgets_weights_and_proposals() {
    let lines = fixture_records("refit");
    let cfg = config::Orchestrator::default();
    let (file, log) = refit(&lines, &TuningFile::default(), &cfg, NOW);
    assert_eq!(
        file.budgets.get("s"),
        Some(&ClassBudget {
            tool_calls: 55,
            minutes: 18,
            tokens: None,
            samples: 34,
            at: NOW,
        })
    );
    assert_eq!(file.budgets.len(), 1, "no M (12 samples) or hub budget");
    assert_eq!(
        file.weights,
        Some(PathWeights {
            s_secs: 550,
            m_secs: 1650,
            hub_secs: 1650,
            derived: vec!["M".into(), "hub".into()],
            at: NOW,
        })
    );
    assert_eq!(file.thresholds, None, "thresholds are only proposed");
    assert!(file.routes.is_empty(), "routes are only proposed");
    assert_eq!(
        log,
        [
            "tuning: budget S 40 calls 15m → 55 calls 18m from 34 samples",
            "tuning: path weights S 550s, M 1650s (derived), hub 1650s (derived)",
        ]
    );
    let proposals = super::proposals(&lines, &file, &cfg);
    let got: Vec<(&str, &str, &str)> = proposals
        .iter()
        .map(|p| (p.id.as_str(), p.current.as_str(), p.proposed.as_str()))
        .collect();
    assert_eq!(
        got,
        [
            ("thresholds.s", "20", "35"),
            ("route.s", "standard/low", "standard/medium")
        ]
    );
    assert_eq!(
        proposals[1].text,
        "S route standard/low → standard/medium (14 of 34 S tasks, 41%, reached rung 2 or higher)"
    );
    // A second refit at a later time changes nothing: within min_change_percent.
    let (again, log) = refit(&lines, &file, &cfg, NOW + 3600);
    assert_eq!(again, file);
    assert!(log.is_empty(), "{log:?}");
}

#[test]
fn one_outlier_run_cannot_move_a_budget_past_its_cap() {
    let lines = fixture_records("outlier-run");
    let cfg = config::Orchestrator::default();
    let (file, _) = refit(&lines, &TuningFile::default(), &cfg, NOW);
    let s = file.budgets["s"];
    assert_eq!(
        (s.tool_calls, s.samples),
        (68, 44),
        "r9 gives its newest 10"
    );
    let mut uncapped = config::Orchestrator::default();
    uncapped.tuning.table.per_run_cap = 1000;
    let (file, _) = refit(&lines, &TuningFile::default(), &uncapped, NOW);
    let s = file.budgets["s"];
    assert_eq!((s.tool_calls, s.samples), (88, 59));
}

#[test]
fn a_small_change_is_kept_not_written() {
    // Median 22 calls and 480 working seconds at a factor of 200: 44 calls 16m.
    let lines: Vec<HistoryLine> = (0..30u32)
        .map(|i| {
            task(record(
                &format!("k{}", i / 10),
                i,
                100 + u64::from(i),
                22,
                480,
                5,
            ))
        })
        .collect();
    let mut cfg = config::Orchestrator::default();
    cfg.tuning.table.budget_factor_percent = 200;
    cfg.tuning.table.path_weights = false;
    let (file, log) = refit(&lines, &TuningFile::default(), &cfg, NOW);
    assert_eq!(file, TuningFile::default(), "44/16 is within 20% of 40/15");
    assert!(log.is_empty(), "{log:?}");
    let r = report(&lines, &file, &cfg, Path::new("/tmp/t/tuning.toml"));
    assert_eq!(r.classes[0].refit, RefitState::Kept);
    assert_eq!(r.classes[0].budget, budget(40, 15));
    // 25% more calls is written.
    cfg.tuning.table.budget_factor_percent = 228; // ceil(22 × 2.28) = 51
    let (file, _) = refit(&lines, &TuningFile::default(), &cfg, NOW);
    assert_eq!(file.budgets["s"].tool_calls, 51);
}

#[test]
fn refit_tokens_only_when_asked() {
    let lines: Vec<HistoryLine> = (0..30u32)
        .map(|i| {
            let mut r = record(&format!("k{}", i / 10), i, 100 + u64::from(i), 20, 600, 5);
            r.worker_usage.input = 1000 + u64::from(i);
            r.worker_usage.output = 1;
            r.reviewer_usage.input = 1_000_000;
            task(r)
        })
        .collect();
    let mut cfg = config::Orchestrator::default();
    let (file, _) = refit(&lines, &TuningFile::default(), &cfg, NOW);
    assert_eq!(file.budgets["s"].tokens, None);
    cfg.tuning.table.refit_tokens = true;
    let (file, _) = refit(&lines, &TuningFile::default(), &cfg, NOW);
    // The worker's billable tokens only: lower median 1015, × 2.5 = 2537.5.
    assert_eq!(file.budgets["s"].tokens, Some(2538));
    let t = tuned(&file, &cfg);
    assert_eq!(t.budget_s.and_then(|b| b.tokens), Some(2538));
    assert_eq!(
        t.log[0],
        "tuning: budget S 50 calls 25m 2.5k tok from 30 samples"
    );
}

#[test]
fn the_rung_4_ceiling_follows_the_effective_m_budget() {
    let mut file = TuningFile::default();
    file.budgets.insert(
        "m".into(),
        ClassBudget {
            tool_calls: 200,
            minutes: 90,
            tokens: None,
            samples: 30,
            at: NOW,
        },
    );
    let cfg = config::Orchestrator::default();
    let t = tuned(&file, &cfg);
    let m = t.effective(&cfg, SizeClass::M);
    assert_eq!(m, budget(200, 90));
    assert_eq!(ceiling(SizeClass::M, m, cfg.budget_l), budget(400, 180));
    assert_eq!(ceiling(SizeClass::Hub, m, cfg.budget_l), budget(400, 180));
    assert_eq!(ceiling(SizeClass::S, m, cfg.budget_l), budget(200, 90));
    // Below half of L, L's budget stays the ceiling.
    let small = budget(100, 50);
    assert_eq!(ceiling(SizeClass::M, small, cfg.budget_l), budget(300, 120));

    let mut configured = config::Orchestrator::default();
    configured.tuning.configured.m = true;
    let t = tuned(&file, &configured);
    let m = t.effective(&configured, SizeClass::M);
    assert_eq!(m, budget(150, 60));
    assert_eq!(
        ceiling(SizeClass::S, m, configured.budget_l),
        budget(150, 60)
    );
    assert_eq!(t.effective(&configured, SizeClass::Hub), budget(150, 60));
}
